# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='foo_bar',
            field=models.CharField(default='foo bar', max_length=32, verbose_name='Foo_Bar'),
        ),
    ]
